### ISSUE TITLE
Not a real issue <3

### ISSUE THREAD

**Issue by yuri-kiss** [CubesterYT/CubesterYT#1]
send me the nitrobolt discord link when you finish it, i should be better by then.

**Comment by yuri-kiss** [comment]
<3

**Comment by CubesterYT** [comment]
No :trollface:

**Comment by yuri-kiss** [comment]
Ok then :+1:

**Comment by CubesterYT** [comment]
😔

**Comment by yuri-kiss** [comment]
I mean you said no soo.

**Comment by CubesterYT** [comment]
@yuri-kiss You can contact me at cubester.spamlegends@gmail.com
I'm deleting this message on GitHub immediately so you only have record of it in your GitHub email notification.
